
export default function PrivacyPolicySection() {
  return (
    <section id="privacy-policy" className="py-12 md:py-24 bg-card">
      <div className="container mx-auto px-4">
        <div className="prose prose-invert max-w-4xl mx-auto">
          <h1>Privacy Policy</h1>
          <p>Last updated: {new Date().toLocaleDateString()}</p>

          <h2>1. Introduction</h2>
          <p>
            Welcome to AppVault ("Company", "we", "our", "us"). We are committed to
            protecting your privacy. This Privacy Policy explains how we
            collect, use, disclose, and safeguard your information when you
            visit our website and use our services (collectively, the "Services"). Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.
          </p>
          <p>
            We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will alert you about any changes by updating the "Last updated" date of this Privacy Policy. You are encouraged to periodically review this Privacy Policy to stay informed of updates. You will be deemed to have been made aware of, will be subject to, and will be deemed to have accepted the changes in any revised Privacy Policy by your continued use of the Services after the date such revised Privacy Policy is posted.
          </p>

          <h2>2. Definitions</h2>
          <p>For the purposes of this Privacy Policy:</p>
          <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
          <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AppVault Inc.</p>
          <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
          <p><strong>Country</strong> refers to: United States</p>
          <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
          <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
          <p><strong>Service</strong> refers to the Website.</p>
          <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
          <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
          <p><strong>Website</strong> refers to AppVault, accessible from this application.</p>
          <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>

          <h2>3. Information We Collect</h2>
          <p>
            We may collect personal information from you in a variety of ways. The information we may collect via the Services depends on the content and materials you use, and includes:
          </p>
          <h3>Personal Data</h3>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, Phone number, Address, State, Province, ZIP/Postal code, City, Billing and payment information, such as credit card details, and Usage Data.
          </p>
          <h3>Usage Data</h3>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
          <h3>Tracking Technologies and Cookies</h3>
          <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include: Cookies or Browser Cookies, Flash Cookies, and Web Beacons.</p>
          
          <h2>4. How We Use Your Information</h2>
          <p>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Services to create and manage your account, process your payments, email you regarding your account, fulfill orders, administer promotions, compile anonymous statistical data, deliver targeted advertising, enable user-to-user communications, generate a personal profile about you, increase the efficiency of the Services, monitor usage and trends, notify you of updates, offer new products, perform other business activities, prevent fraudulent transactions, request feedback, resolve disputes, respond to customer service requests, send you a newsletter, and solicit support for the Services.</p>

          <h2>5. Disclosure of Your Information</h2>
          <p>We may share information we have collected about you in certain situations. Your information may be disclosed as follows: by law or to protect rights, to third-party service providers, for marketing communications with your consent, during business transfers, with our affiliates, and with our business partners to offer you certain products, services, or promotions.</p>
          
          <h2>6. Security of Your Information</h2>
          <p>
            We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse. Any information disclosed online is vulnerable to interception and misuse by unauthorized parties. Therefore, we cannot guarantee complete security if you provide personal information.
          </p>
          
          <h2>7. Policy for Children</h2>
          <p>
            We do not knowingly solicit information from or market to children under the age of 13. If you become aware of any data we have collected from children under age 13, please contact us using the contact information provided below.
          </p>

          <h2>8. Your Data Protection Rights</h2>
          <p>Depending on your location, you may have the following rights regarding your personal data: the right to access, the right to rectification, the right to erasure, the right to restrict processing, the right to object to processing, and the right to data portability. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>

          <h2>9. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please contact
            us at support@appvault.com.
          </p>
        </div>
      </div>
    </section>
  );
}
